// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShopDemo.Core.Data;

#nullable disable

namespace WebShopDemo.Core.Migrations
{
    [DbContext(typeof(WebShopDbContext))]
    partial class WebShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebShopDemo.Core.Data.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasComment("Primary key");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasComment("Product is active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Product name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Product price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Products in stock");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasComment("Products for sale");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abf33c8e-f3aa-4858-b32a-e0a68544e21f"),
                            IsActive = true,
                            Name = "Bread",
                            Price = 2m,
                            Quantity = 100
                        },
                        new
                        {
                            Id = new Guid("6ad9a2a8-3f86-4245-b438-04e366cbc2cc"),
                            IsActive = true,
                            Name = "Beer",
                            Price = 1.5m,
                            Quantity = 200
                        },
                        new
                        {
                            Id = new Guid("7c98ab25-e48c-4c18-8226-9e51abb31018"),
                            IsActive = true,
                            Name = "Ham",
                            Price = 10.45m,
                            Quantity = 40
                        },
                        new
                        {
                            Id = new Guid("2db2cdca-f8a5-49e6-bc82-30ac7a7e723f"),
                            IsActive = true,
                            Name = "Eggs",
                            Price = 3.5m,
                            Quantity = 60
                        },
                        new
                        {
                            Id = new Guid("dc427471-daa0-4d70-9b71-2aa3e16558f9"),
                            IsActive = true,
                            Name = "Milk",
                            Price = 2.35m,
                            Quantity = 35
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
